import { GeistMono } from 'geist/font/mono'
import Header from 'ui-dm-5ive/layouts/header';
import "./globals.css";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${GeistMono.variable}`}>
      <body className='font-mono '>
        <Header />
        {children}
      </body>
    </html>
  );
}
